name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install
    - name: Build bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build
